### ISSUE TITLE
[SUGGESTION] Sorting the Warps in Sledgehammer GUI on server side and not client side.

### ISSUE THREAD

**Issue by Le4nderS** [noahhusby/Sledgehammer#13]
**Is your feature request related to a problem? Please describe.**
When I add a new warp with a city where I already created warps, but after it I created warps in other cities. It ist not sorted under the warps in the same city.

**Describe the solution you'd like**
Its related to the ID numbers. So it should be possible to change the ID numbers or **BETTER** a category system, where you can put warps into categories and not only sorted by servers.

**Comment by noahhusby** [comment]
Implemented in 0.5. 

New server warp groups allow for grouping of warps by server or a custom list of any warps.
