### ISSUE TITLE
[BUG] Deleting warps doesn't actually delete warp

### ISSUE THREAD

**Issue by adammlw** [noahhusby/Sledgehammer#14]
**Describe the bug**
For both the GUI menu for /nwarp, and for the command /nwarp remove <warp>, warps are not actually deleted.

**To Reproduce**
Describe the steps it takes to reproduce the bug
Example:
1. Join the game
2. Teleport to `BTETP-1`
3. Execute command `/nwarp`, and add a new warp
5. Execute command `/nwarp`, and remove the new warp
7. Try teleporting to the warp with /nwarp

Deleted warps will also appear in nwarp menu after GUI reload.

**Expected behavior**
Deleted warps should be deleted.

**Sledgehammer Bungeecord (please complete the following information):**
 - Version: 0.4.1

**Sledgehammer Bukkit (please complete the following information):**
 - Version: 0.4.1
 - Server Backend: Mohist

**Comment by noahhusby** [comment]
Likely an issue with HusbyLib comparator. Should be patched now, please keep track of the issue if it occurs.

**Comment by noahhusby** [comment]
Fixed in https://github.com/noahhusby/Sledgehammer/releases/tag/v0.4.3-beta
