### ISSUE TITLE
Error thrown while executing /cs draw

### ISSUE THREAD

**Issue by Agrrox** [noahhusby/Sledgehammer#2]
Hello, I tried to use one of the craftscripts from [BTE-tools](https://github.com/oganexon/BTE-tools) version 2.0.0 to draw features into minecraft from OSM, and immediately get fatal error message that disconnected me from the server.

[Error_Message.txt](https://github.com/noahhusby/Sledgehammer/files/5287435/Error_Message.txt)

**Comment by noahhusby** [comment]
The bug is likely due to the legacy communication style for tasks trying to be parsed by the JSONParser. I'll replace CSV with a single string for arguments, and test it.

**Comment by noahhusby** [comment]
Fixed in SledgehammerUtil.java
