### ISSUE TITLE
[BUG] Sha setup jumps from 16 to 2

### ISSUE THREAD

**Issue by Rickleuf** [noahhusby/Sledgehammer#3]
**Describe the bug**
If I do /sha setup and use @ to skip servers, after 16 it jumps back to 2.

**To Reproduce**
The steps to reproduce
1. /sha setup
2. @ in chat 16 times

**Expected behavior**
I expected it to go to 17 and further

**Sledgehammer Bungeecord (please complete the following information):**
 - Version: 0.3.1

**Sledgehammer Bukkit (please complete the following information):**
 - Version: 0.3
 - Server Backend: Mohist

**Comment by noahhusby** [comment]
This issue is related to a bug with how bungee cord reports it's servers. I'm using a different system in 0.4 so that's no longer an issue.

The same issue is occurring in 0.4, but likely for a different reason, so I'm keeping this open for now.

**Comment by noahhusby** [comment]
Fixed 17a06449f1c0285cf9711b0109a535cd0849f1d7
