### ISSUE TITLE
craftscript /cs address sends two same messages with single command

### ISSUE THREAD

**Issue by Agrrox** [noahhusby/Sledgehammer#5]
**Describe the bug**
When I use address.js craftscript from BTE-tools, it prints out my current location in terra world, the issue is that it prints the same information twice or it executes twice.

**To Reproduce**
1. join server running BTE-tools and write /cs address

**Expected behavior**
A single message of output is expected

**Screenshots**
![2020-10-04_00 48 52 copy](https://user-images.githubusercontent.com/10901821/95003133-3a0ff380-05dc-11eb-8f7d-f42d33d5cdf0.png)

**Error Logs**
none

**Sledgehammer Bungeecord (please complete the following information):**
 - Version: [e.g. 0.3.0]

**Sledgehammer Bukkit (please complete the following information):**
 - Version: [e.g. 0.3.0]
 - Server Backend: [Mohist 1.12.2]

**Comment by noahhusby** [comment]
Sledgehammer 0.3 is no longer under support due to large changes in the codebase in the upcoming release of 0.4. Please wait for the release of SH 0.4

Could not replicate the issue on 0.4, likely resolved by the new communication system.
