### ISSUE TITLE
[SUGGESTION] Teleportation

### ISSUE THREAD

**Issue by Rickleuf** [noahhusby/Sledgehammer#8]
**Is your feature request related to a problem? Please describe.**
So currently if we would want global teleportation from player to player we would need to add a separate plugin for it, but because everyone already has sledgehammer on the server it would be good to have it in sledgehammer and don't need another plugin.

**Describe the solution you'd like**
Add /tp and /tpa to Sledgehammer and with Redisbungee support.

This would also work nice with terramap when it has bungeecord support because then you can just click on a player and teleport.

**Describe alternatives you've considered**
Other plugins that have these features but we need to add those plugins to all backends and sledgehammer already is on those backend servers.

**Comment by Coppertine** [comment]
BungeeCordServerManager uses a command called /goto <player>
it just switches you to the players server and tp's to them

**Comment by noahhusby** [comment]
This functionality is outside of the scope of this project.
